
ttyoff    : true$
display2d : false$

/*debugmode(true);*/

load("my_functions.mac");

Euu_r0: -(12*si^2*sj^2*(rho*sj^6-2*sj^6+3*rho*si^2*sj^4-6*si^2*sj^4-8*rho*si^3*sj^3+3*rho*si^4*sj^2-6*si^4*sj^2+rho*si^6-2*si^6))/((sj^2+si^2)*(sj^4-2*si*sj^3+6*si^2*sj^2-2*si^3*sj+si^4)*(sj^4+2*si*sj^3+6*si^2*sj^2+2*si^3*sj+si^4));
nu : factor( num(Euu_r0) );  

xxx : mygcd( nu );

div1s: map( factor, divide( xxx[2],  (si^3+sj^3)^2 ) );
d2_: ratsimp( div1s[2]/(si^2*sj^2) );
d2__: complete_square(d2_, si, sj);

ttyoff : false$

print( "mygcd(nu):",  xxx   )$
print( "div1s:",      div1s )$
print( "d2_:",        d2_   )$
print( "d2__:",       d2__  )$
quit()$

/*
xxx: mygcd( nu );
print(nu)$
print_list(nu_facs); 
print(nu);
*/