# LLM Templates Configuration

[deepseek-chat]
api_key_file = "./deepseek.key"
base_url = "https://api.deepseek.com"
model_name = "deepseek-chat"

[gpt-3.5-turbo]
api_key_file = "./openai.key"
base_url = "https://api.openai.com/v1"
model_name = "gpt-3.5-turbo"

[local-llama]
api_key_file = ""
base_url = "http://localhost:8000/v1"
model_name = "llama-7b"

# Add more templates as needed
